#!/usr/bin/env bash
set -e

# install formulae
formulae=()
formulae=("${formulae[@]}" "cowsay")
formulae=("${formulae[@]}" "ctags")
formulae=("${formulae[@]}" "figlet")
formulae=("${formulae[@]}" "fzf")
formulae=("${formulae[@]}" "git")
formulae=("${formulae[@]}" "gnupg")
formulae=("${formulae[@]}" "golang")
formulae=("${formulae[@]}" "hub")
formulae=("${formulae[@]}" "lolcat")
formulae=("${formulae[@]}" "mas")
formulae=("${formulae[@]}" "neovim")
formulae=("${formulae[@]}" "tmux")
formulae=("${formulae[@]}" "zsh")

for formula in "${formulae[@]}"; do
  if brew ls --versions $formula > /dev/null; then continue; fi

  echo "Installing $formula"
  brew install $formula
done