name: embark
root: ~/src/github.com/embark-framework/embark/
startup_window: editor
pre_window: export EMBARK_NO_SHIM=true; clear
windows:
  - babel:
      layout: main-vertical
      panes:
        - yarn run watch
        - cd packages/embark-ui; yarn start
  - demo:
      root: ~/src/_sandbox/embark_demo
      panes:
  - editor:
      panes:
        - nvim
  - tests:
      panes:
