add_newline = false
format = "$directory$git_branch$git_status [>](bold red) "

[directory]
fish_style_pwd_dir_length = 1
style = "bold blue"

[git_branch]
format = "[$branch]($style)"
style = "bold yellow"

[git_status]
format = "[$staged$modified](red)"
modified = "*"
staged = "!"

[git_state]
format = "[($state)](red)"
