#!/usr/bin/env bash
set -e

# ensure we're in the correct path
cd "$(dirname "$0")/.."

# install homebrew if it's missing
if [ ! -f "/opt/homebrew/bin/brew" ]; then
  echo "Installing homebrew"
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# ensure brew environment
eval $(/opt/homebrew/bin/brew shellenv)

if ! brew ls --versions rcm > /dev/null; then
  echo "Installing rcm"
  brew install rcm
fi


# and liftoff!
env RCRC="$(pwd)"/rcrc rcup

# setup the git origin so that I can actually push stuff
git remote set-url origin git@github.com:andremedeiros/dotfiles.git
