#!/usr/bin/env bash
set -e

# disable key hold popup
defaults write -g ApplePressAndHoldEnabled -bool false

# make repetitions super fast
defaults write -g InitialKeyRepeat -int 10
defaults write -g KeyRepeat -int 1

# dock goes on the left
defaults write com.apple.dock orientation -string left

# and we're done
killall Dock