#!/usr/bin/env bash
set -e

#                       ________    _________
#   _____ _____    ____ \_____  \  /   _____/
#  /     \\__  \ _/ ___\ /   |   \ \_____  \
# |  Y Y  \/ __ \\  \___/    |    \/        \
# |__|_|  (____  /\___  >_______  /_______  /
#       \/     \/     \/        \/        \/

# disable key hold popup
defaults write -g ApplePressAndHoldEnabled -bool false

# make repetitions super fast
defaults write -g InitialKeyRepeat -int 15
defaults write -g KeyRepeat -int 1

# dock goes on the left
defaults write com.apple.dock orientation -string left

# disable automatic capitalization and smart quotes as they're annoying when writing code
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

# enable subpixel font rendering on non-Apple LCDs
defaults write NSGlobalDomain AppleFontSmoothing -int 2

# use a dark menu bar and dock
defaults write NSGlobalDomain AppleInterfaceStyle -string "Dark"

# tap to click, please
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true

# don't open photos.app every time I plug in a device
defaults write com.apple.ImageCapture disableHotPlug -bool YES

# automatically hide and show the dock
defaults write com.apple.Dock autohide -bool true

# show the dock quickly
defaults write com.apple.Dock autohide-delay -float 0

# hide recent applications
defaults write com.apple.Dock show-recents -bool false

# expand save dialog by default
defaults write -g NSNavPanelExpandedStateForSaveMode -bool true
defaults write -g NSNavPanelExpandedStateForSaveMode2 -bool true

# only show scrollbar when scrolling
defaults write -g AppleShowScrollBars -string "WhenScrolling"

# don't write .DS_Store
defaults write com.apple.desktopservices DSDontWriteNetworkStores true

# don't screw up fonts
defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO

#   _________       _____             .__
#  /   _____/____ _/ ____\____ _______|__|
#  \_____  \\__  \\   __\\__  \\_  __ \  |
#  /        \/ __ \|  |   / __ \|  | \/  |
# /_______  (____  /__|  (____  /__|  |__|
#         \/     \/           \/
defaults write com.apple.Safari.SandboxBroker ShowDevelopMenu -bool false

# ___________                  .__              .__
# \__    ___/__________  _____ |__| ____ _____  |  |
#   |    |_/ __ \_  __ \/     \|  |/    \\__  \ |  |
#   |    |\  ___/|  | \/  Y Y  \  |   |  \/ __ \|  |__
#   |____| \___  >__|  |__|_|  /__|___|  (____  /____/
#              \/            \/        \/     \/

# add jellybeans theme
defaults read com.apple.Terminal "Window Settings" | (grep -q Jellybeans || open ~/Downloads/Jellybeans.terminal)
defaults write com.apple.Terminal "Default Window Settings" -string "Jellybeans"
defaults write com.apple.Terminal "Startup Window Settings" -string "Jellybeans"

# ._____________                   ________
# |__\__    ___/__________  _____  \_____  \
# |  | |    |_/ __ \_  __ \/     \  /  ____/
# |  | |    |\  ___/|  | \/  Y Y  \/       \
# |__| |____| \___  >__|  |__|_|  /\_______ \
#                 \/            \/         \/

# use dark ui
defaults write com.googlecode.iterm2 TabStyle -int 1

# add jellybeans theme
defaults read com.googlecode.iterm2 "Custom Color Presets" | (grep -q jellybeans || open ~/Downloads/jellybeans.itermcolors)

# don't confirm whether I want to quit
defaults write com.googlecode.iterm2 PromptOnQuit -bool false
defaults write com.googlecode.iterm2 OnlyWhenMoreTabs -bool false

#   ___ ___
#  /   |   \_____    _____   _____   ___________  ____________   ____   ____   ____
# /    ~    \__  \  /     \ /     \_/ __ \_  __ \/  ___/\____ \ /  _ \ /  _ \ /    \
# \    Y    // __ \|  Y Y  \  Y Y  \  ___/|  | \/\___ \ |  |_> >  <_> |  <_> )   |  \
#  \___|_  /(____  /__|_|  /__|_|  /\___  >__|  /____  >|   __/ \____/ \____/|___|  /
#        \/      \/      \/      \/     \/           \/ |__|                      \/

defaults write org.hammerspoon.Hammerspoon MJShowDockIconKey -bool false
defaults write org.hammerspoon.Hammerspoon MJShowMenuIconKey -bool false
defaults write org.hammerspoon.Hammerspoon MJKeepConsoleOnTopKey -bool true

#    _____                    _________ __
#   /  _  \ ______ ______    /   _____//  |_  ___________   ____
#  /  /_\  \\____ \\____ \   \_____  \\   __\/  _ \_  __ \_/ __ \
# /    |    \  |_> >  |_> >  /        \|  | (  <_> )  | \/\  ___/
# \____|__  /   __/|   __/  /_______  /|__|  \____/|__|    \___  >
#         \/|__|   |__|             \/                         \/

# check for updates daily
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# download updates on the background
defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1

# turn on auto-update
defaults write com.apple.commerce AutoUpdate -bool true

#   _________              __  .__  .__       .__     __
#  /   _____/_____   _____/  |_|  | |__| ____ |  |___/  |_
#  \_____  \\____ \ /  _ \   __\  | |  |/ ___\|  |  \   __\
#  /        \  |_> >  <_> )  | |  |_|  / /_/  >   Y  \  |
# /_______  /   __/ \____/|__| |____/__\___  /|___|  /__|
#         \/|__|                      /_____/      \/

# be selective on things we do index
defaults write com.apple.spotlight orderedItems -array \
  '{"enabled" = 1;"name" = "APPLICATIONS";}' \
  '{"enabled" = 1;"name" = "SYSTEM_PREFS";}' \
  '{"enabled" = 1;"name" = "DIRECTORIES";}' \
  '{"enabled" = 0;"name" = "PDF";}' \
  '{"enabled" = 0;"name" = "FONTS";}' \
  '{"enabled" = 0;"name" = "DOCUMENTS";}' \
  '{"enabled" = 0;"name" = "MESSAGES";}' \
  '{"enabled" = 0;"name" = "CONTACT";}' \
  '{"enabled" = 0;"name" = "EVENT_TODO";}' \
  '{"enabled" = 0;"name" = "IMAGES";}' \
  '{"enabled" = 0;"name" = "BOOKMARKS";}' \
  '{"enabled" = 0;"name" = "MUSIC";}' \
  '{"enabled" = 0;"name" = "MOVIES";}' \
  '{"enabled" = 0;"name" = "PRESENTATIONS";}' \
  '{"enabled" = 0;"name" = "SPREADSHEETS";}' \
  '{"enabled" = 0;"name" = "SOURCE";}' \
  '{"enabled" = 0;"name" = "MENU_DEFINITION";}' \
  '{"enabled" = 0;"name" = "MENU_OTHER";}' \
  '{"enabled" = 0;"name" = "MENU_CONVERSION";}' \
  '{"enabled" = 0;"name" = "MENU_EXPRESSION";}' \
  '{"enabled" = 0;"name" = "MENU_WEBSEARCH";}' \
  '{"enabled" = 0;"name" = "MENU_SPOTLIGHT_SUGGESTIONS";}'

# ________                 __                .__
# \______ \   _______  ___/  |_  ____   ____ |  |   ______
#  |    |  \_/ __ \  \/ /\   __\/  _ \ /  _ \|  |  /  ___/
#  |    `   \  ___/\   /  |  | (  <_> |  <_> )  |__\___ \
# /_______  /\___  >\_/   |__|  \____/ \____/|____/____  >
#         \/     \/                                    \/
sudo /usr/sbin/DevToolsSecurity --enable

# and we're done
apps=()
apps=("${apps[@]}" "Dock")
apps=("${apps[@]}" "Safari")
apps=("${apps[@]}" "mds")

for app in "${apps[@]}"; do
  killall "${app}" &> /dev/null
done
