#!/usr/bin/env bash

# make sure we have our path set on a run previous to having a full environment
export GOPATH=$HOME/.go

# so compilers can find zlib
export LDFLAGS="-L$HOMEBREW_PREFIX/opt/zlib/lib"
export CPPFLAGS="-I$HOMEBREW_PREFIX/opt/zlib/include"

mise install
