#!/usr/bin/env bash

# make sure we have our path set on a run previous to having a full environment
export GOPATH=$HOME/.go

# so compilers can find zlib
export LDFLAGS="-L$HOMEBREW_PREFIX/opt/zlib/lib"
export CPPFLAGS="-I$HOMEBREW_PREFIX/opt/zlib/include"

plugins=()
plugins=("${plugins[@]}" "elm")
plugins=("${plugins[@]}" "gohugo")
plugins=("${plugins[@]}" "golang")
plugins=("${plugins[@]}" "nodejs")
plugins=("${plugins[@]}" "python")
plugins=("${plugins[@]}" "ruby")
plugins=("${plugins[@]}" "rust")
plugins=("${plugins[@]}" "yarn")

for plugin in "${plugins[@]}"; do
  (asdf plugin-list | grep "$plugin") || asdf plugin-add "$plugin"
done

# some plugin requirements
~/.asdf/plugins/nodejs/bin/import-release-team-keyring

for plugin in "${plugins[@]}"; do
  asdf install "$plugin" $(cat ~/.tool-versions | grep "$plugin" | awk '{print $2}')
done
