#!/usr/bin/env bash
set -e

# ensure directories exist
autoload_root=$(realpath -m ~/.config/nvim/autoload)
bundle_root=$(realpath -m ~/.config/nvim/bundle)

mkdir -p $autoload_root $bundle_root

# ensure pathogen is installed
curl -LSso $autoload_root/pathogen.vim https://tpo.pe/pathogen.vim

plugins=()

# Language / Syntax
plugins=("${plugins[@]}" "fatih/vim-go") # Go

for plugin in "${plugins[@]}"; do
  repo="https://github.com/${plugin}.git"
  base=$(basename $plugin)

  if [ -d "$bundle_root/$base" ]; then
    git -C $bundle_root/$base pull >/dev/null
  else
    git -C $bundle_root clone $repo >/dev/null
  fi
done