#!/usr/bin/env bash
set -e

nvim_root=${HOME}/.config/nvim
minpac_root=${nvim_root}/pack/minpac/opt/minpac

if [ ! -d "${minpac_root}" ]; then
  # ensure directories exist
  mkdir -p "$minpac_root"

  # ensure minpac is installed
  git clone https://github.com/k-takata/minpac.git ${minpac_root}
fi

nvim --headless -c PackInstall
