#!/usr/bin/env bash
set -e

# ensure directories exist
nvim_root=${HOME}/.config/nvim
autoload_root=${nvim_root}/autoload
bundle_root=${nvim_root}/bundle

mkdir -p "$autoload_root" "$bundle_root"

# ensure pathogen is installed
curl -LSso "$autoload_root/pathogen.vim" https://tpo.pe/pathogen.vim

plugins=()

# language / syntax
plugins=("${plugins[@]}" "ElmCast/elm-vim")
plugins=("${plugins[@]}" "andremedeiros/ragel.vim")
plugins=("${plugins[@]}" "fatih/vim-go")
plugins=("${plugins[@]}" "isRuslan/vim-es6")
plugins=("${plugins[@]}" "leafgarland/typescript-vim")
plugins=("${plugins[@]}" "tomlion/vim-solidity")
plugins=("${plugins[@]}" "vim-ruby/vim-ruby")
plugins=("${plugins[@]}" "w0rp/ale")

# colorschemes / ui
plugins=("${plugins[@]}" "Xuyuanp/nerdtree-git-plugin")
plugins=("${plugins[@]}" "airblade/vim-gitgutter")
plugins=("${plugins[@]}" "itchyny/lightline.vim")
plugins=("${plugins[@]}" "maximbaz/lightline-ale")
plugins=("${plugins[@]}" "mhinz/vim-startify")
plugins=("${plugins[@]}" "nanotech/jellybeans.vim")
plugins=("${plugins[@]}" "romainl/vim-qf")
plugins=("${plugins[@]}" "scrooloose/nerdtree")
plugins=("${plugins[@]}" "troydm/zoomwintab.vim")

# file management / browsing
plugins=("${plugins[@]}" "junegunn/fzf.vim")
plugins=("${plugins[@]}" "majutsushi/tagbar")
plugins=("${plugins[@]}" "tpope/vim-fugitive")
plugins=("${plugins[@]}" "tpope/vim-rhubarb")

# helpers
plugins=("${plugins[@]}" "tpope/vim-endwise")
plugins=("${plugins[@]}" "tpope/vim-surround")

for plugin in "${plugins[@]}"; do
  repo="https://github.com/${plugin}.git"
  base=$(basename "$plugin")

  if [ -d "$bundle_root/$base" ]; then
    git -C "$bundle_root/$base" pull &> /dev/null
  else
    git -C "$bundle_root" clone "$repo" &> /dev/null
  fi
done
