#!/usr/bin/env bash
set -e

# make sure we have our path set on a run previous to having a full environment
export GOPATH=$HOME

packages=()
packages=("${packages[@]}" "github.com/derekparker/delve/cmd/dlv")
packages=("${packages[@]}" "github.com/golang/dep/cmd/dep")
packages=("${packages[@]}" "github.com/golang/lint/golint")
packages=("${packages[@]}" "github.com/google/pprof")
packages=("${packages[@]}" "github.com/jstemmer/gotags")
packages=("${packages[@]}" "github.com/kisielk/errcheck")
packages=("${packages[@]}" "github.com/mdempsky/gocode")
packages=("${packages[@]}" "honnef.co/go/tools/cmd/gosimple")

for package in "${packages[@]}"; do
  go get -u "$package"
done
