#!/usr/bin/env bash
set -e

# export so that installing go binaries does that
# in the right place
export GOPATH=$HOME/.go

if [ ! -d ~/.local/share/nvim/site/pack/packer ]; then
  # ensure packer is installed
  git clone --depth 1 https://github.com/wbthomason/packer.nvim\
   ~/.local/share/nvim/site/pack/packer/start/packer.nvim
fi
