#!/usr/bin/env bash
set -e

terminfo=$(mktemp /tmp/terminfo.XXXXXX)
cat << EOF > "$terminfo"
xterm-256color|xterm with 256 colors and italic,
  sitm=\E[3m, ritm=\E[23m,
  use=xterm-256color,
EOF

tmux_terminfo=$(mktemp /tmp/tmux_terminfo.XXXXXX)
cat << EOF > "$tmux_terminfo"
tmux-256color|tmux with 256 colors,
  ritm=\E[23m, rmso=\E[27m, sitm=\E[3m, smso=\E[7m, Ms@,
  khome=\E[1~, kend=\E[4~,
  use=xterm-256color, use=screen-256color,
EOF

tic -x "$terminfo"
tic -x "$tmux_terminfo"
rm "$terminfo"
rm "$tmux_terminfo"
