#!/usr/bin/env zsh
set -e

# make sure we have our path set on a run previous to having a full environment
eval "$(rtx activate)"
export GOPATH=$HOME/.go

# golang
packages=()
packages=("${packages[@]}" "github.com/go-delve/delve/cmd/dlv")
packages=("${packages[@]}" "github.com/google/pprof")
packages=("${packages[@]}" "github.com/jstemmer/gotags")
packages=("${packages[@]}" "github.com/kisielk/errcheck")
packages=("${packages[@]}" "github.com/mdempsky/gocode")
packages=("${packages[@]}" "golang.org/x/lint/golint")
packages=("${packages[@]}" "golang.org/x/tools/gopls")

for package in "${packages[@]}"; do
  go install "$package"@latest
done

# nodejs
packages=()
packages=("${packages[@]}" "dockerfile-language-server-nodejs")
packages=("${packages[@]}" "elm-format")
packages=("${packages[@]}" "elm-oracle")
packages=("${packages[@]}" "elm-test")
packages=("${packages[@]}" "typescript")
packages=("${packages[@]}" "typescript-language-server")

for package in "${packages[@]}"; do
  npm install -g "$package"
done

# ruby
packages=()
packages=("${packages[@]}" "solargraph")
packages=("${packages[@]}" "rufo")

for package in "${packages[@]}"; do
  gem install "$package"
done
