#!/usr/bin/env bash
set -e

# make sure we have our path set on a run previous to having a full environment
export PATH=$HOME/.asdf/shims:$PATH
export GOPATH=$HOME/.go

# golang
packages=()
packages=("${packages[@]}" "github.com/go-delve/delve/cmd/dlv")
packages=("${packages[@]}" "github.com/golang/dep/cmd/dep")
packages=("${packages[@]}" "github.com/google/pprof")
packages=("${packages[@]}" "github.com/jstemmer/gotags")
packages=("${packages[@]}" "github.com/kisielk/errcheck")
packages=("${packages[@]}" "github.com/mdempsky/gocode")
packages=("${packages[@]}" "github.com/sourcegraph/go-langserver")
packages=("${packages[@]}" "golang.org/x/lint/golint")
packages=("${packages[@]}" "golang.org/x/tools/cmd/gopls")

for package in "${packages[@]}"; do
  brew gomod "$package" || true
done

# nodejs
packages=()
packages=("${packages[@]}" "dockerfile-language-server-nodejs")
packages=("${packages[@]}" "elm-format")
packages=("${packages[@]}" "elm-oracle")
packages=("${packages[@]}" "elm-test")
packages=("${packages[@]}" "typescript")
packages=("${packages[@]}" "typescript-language-server")

for package in "${packages[@]}"; do
  npm install -g "$package"
done

# ruby
packages=()
packages=("${packages[@]}" "solargraph")

for package in "${packages[@]}"; do
  gem install "$package"
done
