#!/usr/bin/env bash
set -e

if [ "$SHELL" != "$HOMEBREW_PREFIX/bin/fish" ]; then
  grep -qx "$HOMEBREW_PREFIX/bin/fish" /etc/shells || echo "$HOMEBREW_PREFIX/bin/fish" | sudo tee -a /etc/shells
  sudo dscl . -create /Users/"$USER" UserShell $HOMEBREW_PREFIX/bin/fish
fi

fisher install jethrokuan/z

fish_config theme choose "ayu Dark"
fish_config theme save
