#!/usr/bin/env bash
set -e

# create ~/.nvm
mkdir -p ~/.nvm

# load nvm in case it's not already loaded
source /usr/local/opt/nvm/nvm.sh

# install node version specified in ~/.nvm
nvm install $(cat ~/.nvmrc)
npm i -g npm@latest
