#!/usr/bin/env bash
set -e

docsets=()
docsets=("${docsets[@]}" "Bash")
docsets=("${docsets[@]}" "C")
docsets=("${docsets[@]}" "Docker")
docsets=("${docsets[@]}" "Elixir")
docsets=("${docsets[@]}" "Go")
docsets=("${docsets[@]}" "JavaScript")
docsets=("${docsets[@]}" "NodeJS")
docsets=("${docsets[@]}" "Redis")
docsets=("${docsets[@]}" "Ruby_2")

for docset in "${docsets[@]}"; do
  url="http://newyork.kapeli.com/feeds/$docset.tgz"

  curl -o "/tmp/$docset.tgz" $url
  open -jW "/tmp/$docset.tgz"
  rm "/tmp/$docset.tgz"
done

open /tmp/*.docset
rm -rf /tmp/*.docset
