#!/usr/bin/env bash
set -e

# set up bitwarden
bw login --check && bw logout
bw config server https://passwords.home.andre.cool/
export BW_SESSION="$(bw login hello@andre.cool --raw)"

# get secrets
bw get item 9bf39747-2bc6-4a11-8271-8b68c3aa8602 | jq -r .notes > ~/.ssh/id_rsa
bw get item f09172d0-b10c-4313-8f81-258e4e023bbf | jq -r .notes > ~/.gnupg/gpg.private.key

# set proper permissions on ~/.ssh
chmod 600 ~/.ssh/id_*
chmod 700 ~/.ssh

# ensure ~/.gnupg is set up and has good perms
mkdir -p ~/.gnupg
chmod 700 ~/.gnupg

# import GPG secret key
gpg --import ~/.gnupg/gpg.private.key

# clear secret key
rm ~/.gnupg/gpg.private.key
