#!/usr/bin/env bash
set -e

plugins=()
# utils
plugins=("${plugins[@]}" "ms-vsliveshare.vsliveshare")
plugins=("${plugins[@]}" "vscodevim.vim")

# language / syntax
plugins=("${plugins[@]}" "juanblanco.solidity")
plugins=("${plugins[@]}" "ms-vscode.cpptools")
plugins=("${plugins[@]}" "ms-vscode.go")
plugins=("${plugins[@]}" "sbrink.elm")

# colorschemes / ui
plugins=("${plugins[@]}" "andrsdc.base16-themes")
plugins=("${plugins[@]}" "equinusocio.vsc-material-theme")

# helpers
plugins=("${plugins[@]}" "editorconfig.editorconfig")

for plugin in "${plugins[@]}"; do
  code --force --install-extension "$plugin"
done
