[tools]
"github:golang-migrate/migrate" = "latest"
"github:golangci/golangci-lint" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/kisielk/errcheck" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@github/copilot" = "latest"
"npm:@openai/codex" = "latest"
"npm:opencode-ai" = "latest"
"npm:@opengsd/gsd-core" = "latest"
"npm:@oh-my-pi/pi-coding-agent" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:elm-format" = "latest"
"npm:elm-test" = "latest"
"github:elm/compiler[exe=elm]" = "latest"
"npm:typescript" = "latest"
"gem:solargraph" = "latest"
"gem:rufo" = "latest"
node = "latest"
bun = "latest"
